In [1]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier


In [2]:
df=pd.read_csv("drug200.csv")

In [3]:
df.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

In [4]:
x=df[["Age","Sex","BP","Cholesterol","Na_to_K"]].values
x[:5]


array([[23, 'F', 'HIGH', 'HIGH', 25.355],
       [47, 'M', 'LOW', 'HIGH', 13.093],
       [47, 'M', 'LOW', 'HIGH', 10.114],
       [28, 'F', 'NORMAL', 'HIGH', 7.798],
       [61, 'F', 'LOW', 'HIGH', 18.043]], dtype=object)

In [5]:
from sklearn import preprocessing

le_sex=preprocessing.LabelEncoder()
le_sex.fit(["F","M"])
x[:,1] = le_sex.transform(x[:,1])

le_BP=preprocessing.LabelEncoder()
le_BP.fit(["HIGH","LOW","NORMAL"])
x[:,2] = le_BP.transform(x[:,2])

le_Cholesterol=preprocessing.LabelEncoder()
le_Cholesterol.fit(["NORMAL","HIGH"])
x[:,3] = le_Cholesterol.transform(x[:,3])

x[:5]

array([[23, 0, 0, 0, 25.355],
       [47, 1, 1, 0, 13.093],
       [47, 1, 1, 0, 10.114],
       [28, 0, 2, 0, 7.798],
       [61, 0, 1, 0, 18.043]], dtype=object)

In [6]:
y=df["Drug"]
y[0:5]

0    drugY
1    drugC
2    drugC
3    drugX
4    drugY
Name: Drug, dtype: object

In [16]:
x

array([[23, 0, 0, 0, 25.355],
       [47, 1, 1, 0, 13.093],
       [47, 1, 1, 0, 10.114],
       [28, 0, 2, 0, 7.798],
       [61, 0, 1, 0, 18.043],
       [22, 0, 2, 0, 8.607],
       [49, 0, 2, 0, 16.275],
       [41, 1, 1, 0, 11.037],
       [60, 1, 2, 0, 15.171],
       [43, 1, 1, 1, 19.368],
       [47, 0, 1, 0, 11.767],
       [34, 0, 0, 1, 19.199],
       [43, 1, 1, 0, 15.376],
       [74, 0, 1, 0, 20.942],
       [50, 0, 2, 0, 12.703],
       [16, 0, 0, 1, 15.516],
       [69, 1, 1, 1, 11.455],
       [43, 1, 0, 0, 13.972],
       [23, 1, 1, 0, 7.298],
       [32, 0, 0, 1, 25.974],
       [57, 1, 1, 1, 19.128],
       [63, 1, 2, 0, 25.917],
       [47, 1, 1, 1, 30.568],
       [48, 0, 1, 0, 15.036],
       [33, 0, 1, 0, 33.486],
       [28, 0, 0, 1, 18.809],
       [31, 1, 0, 0, 30.366],
       [49, 0, 2, 1, 9.381],
       [39, 0, 1, 1, 22.697],
       [45, 1, 1, 0, 17.951],
       [18, 0, 2, 1, 8.75],
       [74, 1, 0, 0, 9.567],
       [49, 1, 1, 1, 11.014],
       [65, 0, 0,

In [7]:
from sklearn.model_selection import train_test_split

train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.3,random_state=100)


In [8]:
drugtree= DecisionTreeClassifier(criterion="entropy",max_depth=4)
drugtree

DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [9]:
drugtree.fit(train_x,train_y)

DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [10]:
predtree=drugtree.predict(test_x)
print(test_y[0:5])
    print(predtree[0:5])

126    drugY
104    drugY
99     drugY
92     drugY
111    drugX
Name: Drug, dtype: object
['drugY' 'drugY' 'drugY' 'drugY' 'drugX']


C:\Users\kavosh-lp\AppData\Local\Temp\ipykernel_7360\1562368762.py:2: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  print(test_y[0:5])


In [11]:
from sklearn import metrics
import matplotlib.pyplot as plt
print("Decition trees Accuuracy:",metrics.accuracy_score(test_y,predtree))

Decition trees Accuuracy: 0.9833333333333333
